services:
  db:
    image: flask/mysql:1.0
    build: ./db
    container_name: 'flask-db'
    expose: 
      - "3306"
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../db/database:/var/lib/mysql
      - ../db/init:/docker-entrypoint-initdb.d
  web:
    image: flask/web:1.0
    build: ./web
    container_name: 'flask-web'
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    volumes:
      - ../web:/home/user1/dev
 